version: "3.2"
services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile-database
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: on-failure
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
  web:
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.backend
      target: development
    depends_on:
      - db
    ports:
      - 127.0.0.1:4000:4000
    restart: on-failure
    volumes:
      - type: bind
        source: .
        target: /code
  rebuilder:
    build:
      context: ./
      dockerfile: Dockerfiles/Dockerfile.frontend
      target: rebuilder
    volumes:
      - type: bind
        source: .
        target: /code
