name: Publish Docker image
on:
  push:
    branches:
      - master
      - develop
  release:
    types: [published]
jobs:
  push_to_registry:
    if: github.repository == 'ScilifelabDataCentre/SweFreq'
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Dockerfiles/Dockerfile.backend
          context: .
          target: production
          push: true
          tags: scilifelabdatacentre/swefreq-backend:${{ steps.docker-tag.outputs.tag }}
      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Dockerfiles/Dockerfile.frontend
          context: .
          target: production
          push: true
          tags: scilifelabdatacentre/swefreq-frontend:${{ steps.docker-tag.outputs.tag }}
